subject: implementation  of Winc-Academy-feedback-round-1 on Superpy: subparser show_cost // subparser show_bought_csv
1. feedback: 'subparser show_cost' not showing any results
    feedback-video: 9min:46sec (between 09min:46s and the 10min:28s) https://vimeo.com/869581020/d1759c34db
    rootcause of the problem: the entire following 'show_cost' code block in super.py was intended to the right with 1 tab too much:
        # nr 8of16
        if args.command == "show_cost":
        path_to_directory_testdata = ''
        path_to_directory_testdata = get_path_to_directory_of_file('data_used_in_superpy')
        path_to_file_bought_csv = os.path.join(path_to_directory_testdata, 'bought.csv')
        cost = calculate_cost_in_time_range_between_start_date_and_end_date_inclusive(args.start_date, args.end_date, path_to_file_bought_csv)
        print('---------------------------------------------------------------------------------------------------')
        print('                                                                                                   ')
        print(f" Current action in Superpy: show_cost                                                            ")
        print(f" host machine: {socket.gethostname()}                                                            ")
        print(f" host machine date: {datetime.now().date()} ({show_weekday_from_date(datetime.now().date().strftime('%Y-%m-%d'))})")
        print(f" Superpy SYSTEM_DATE: {SYSTEM_DATE} ({show_weekday_from_date(SYSTEM_DATE)})")
        print('                                                                                                   ')
        print(f"Cost from start_date: {args.start_date} to end_date: {args.end_date} inclusive: Euro {cost}")
        print('                                                                                                   ')
        print('---------------------------------------------------------------------------------------------------')
    solution: shift-tab this block of code 1 tab to the left

2. feedback: 'subparser show_bought_csv' shows correct info, but also shows an error:
    "cost = calculate_cost_in_time_range_between_start_date_and_end_date_inclusive(args.start_date, args.end_date, path_to_file_bought.csv)
    and then:
    "AttributeError: 'Namespace' object has no attribute 'start_date'"

    feedback-video: 8min:38sec (between 08min:08s and the 9min:25s) https://vimeo.com/869581020/d1759c34db

    cause of the bug: code block 'show_cost' was indented 1 tab too  much to the right (see feedback above). As a result of that the code looked  like this:

        if args.command == "show_bought_csv":
            path_to_directory_testdata = ''
            path_to_directory_testdata = get_path_to_directory_of_file('data_used_in_superpy')
            path_to_file_bought_csv = os.path.join(path_to_directory_testdata, 'bought.csv')
            show_csv_file_in_console_with_module_rich(path_to_file_bought_csv)

        # nr 8of16
            if args.command == "show_cost":
                path_to_directory_testdata = ''
                path_to_directory_testdata = get_path_to_directory_of_file('data_used_in_superpy')
                path_to_file_bought_csv = os.path.join(path_to_directory_testdata, 'bought.csv')
                cost = calculate_cost_in_time_range_between_start_date_and_end_date_inclusive(args.start_date, args.end_date, path_to_file_bought_csv)
                print('---------------------------------------------------------------------------------------------------')
                print('                                                                                                   ')
                print(f" Current action in Superpy: show_cost                                                            ")
                print(f" host machine: {socket.gethostname()}                                                            ")
                print(f" host machine date: {datetime.now().date()} ({show_weekday_from_date(datetime.now().date().strftime('%Y-%m-%d'))})")
                print(f" Superpy SYSTEM_DATE: {SYSTEM_DATE} ({show_weekday_from_date(SYSTEM_DATE)})")
                print('                                                                                                   ')
                print(f"Cost from start_date: {args.start_date} to end_date: {args.end_date} inclusive: Euro {cost}")
                print('                                                                                                   ')
                print('---------------------------------------------------------------------------------------------------')

    So what happened (before the quick fix above) is that show_bought_csv also triggers the code in show_cost.
    solution: shift-tab this show_cost block of code 1 tab to the left (see feedback above)